[[carousels]]
  banner = "https://user-images.githubusercontent.com/38887077/77512987-09256800-6eaf-11ea-9b41-e8b87ab51fe8.png"
  description = "How Nebula Graph Automatically Cleans Stale Data with TTL"
  link = "/en/posts/clean-stale-data-with-ttl-in-nebula-graph_/"
[[carousels]]
  banner = "https://user-images.githubusercontent.com/38887077/76831941-482a3c80-6863-11ea-9795-009eaa50fc0e.png"
  description = "Automating Your Project Processes with Github Actions"
  link = "/en/posts/github-action-automating-project-process/"