################ English Config ################
contentDir = "content/en"
[params]

  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more information take a look at the README.

  # To provide some metadata for search engines feel free to add some
  # information about you and your website.

  description = "Featuring horizontal scalability, strong data consistency, high availability, and SQL-like query language, Nebula Graph database enables you to get insight out of your connected data. Get it now. For free"
  name = "Nebula Graph"

  # The path must be relative to the static folder

  favicon = "favicon.ico"

  blogTitle = "Nebula Graph Blog"
  postsTitle = "Latest Nebula Graph Posts"
  readAll ="Read more"

  backBlogs = "Back to blog home"

  # Navigation
  [params.navigation]
    brand = "NebulaGraph"

    [[params.navigation.links]]
      title = "Use Cases"
      class = "dropdown dropdown-left"
        [[params.navigation.links.case]]
          title = "Real-time Recommendation"
          link = "/real-time-recommendation/"
        [[params.navigation.links.case]]
          title = "Fraud Detection"
          link = "/fraud-detection/"
        [[params.navigation.links.case]]
          title = "Cyber Security"
          link = "/cyber-security/"
        [[params.navigation.links.case]]
          title = "AI and Machine Learning"
          link = "/ai-and-machine-learning/"
    [[params.navigation.links]]
      title = "Docs"
      link = "https://docs.nebula-graph.io/"
      target = "_blank"
    [[params.navigation.links]]
      title = "Blog"
      link = "/posts"
    [[params.navigation.links]]
      title = "Forum"
      link = "https://discuss.nebula-graph.io/"
      target = "_blank"
    [[params.navigation.links]]
      title = "Company"
      class = "dropdown dropdown-left"
      [[params.navigation.links.case]]
        title = "Newsroom"
        link = "/news"
      [[params.navigation.links.case]]
        title = "Contact Us"
        link = "mailto:info@vesoft.com"
      # [[params.navigation.links.links]]
      # 	title = "Use cases"
    # [[params.navigation.links]]
    # 	title = "Customers"
    [[params.navigation.links]]
      pic = "language120x120.png"
      class = "dropdown"
        [[params.navigation.links.links]]
          title = "English"
          link = "/en/"
        [[params.navigation.links.links]]
          title = "中文"
          link = "/cn/"
    [[params.navigation.links]]
        title = "Nebula Studio"
        link = "https://github.com/vesoft-inc/nebula-web-docker"
        calss= "navbar-right"
        onclick = "gtag('event', 'Button Click', { event_category: 'Engagement', event_label: 'Nebula Studio'})"
        target = "_blank"

  # Hero section
  [params.header]
    # To change the background of the header section, replace the 'header.jpg' at './static/img' with your own.
    slogan     = "A Powerfully Distributed, Scalable, Lightning-Fast Graph Database"
    subtitle   = "Nebula Graph is an open-source graph database unmatched in its ability to host super large-scale graphs using billions of vertices (nodes) and trillions of edges with milliseconds of latency. This empowers businesses to reveal untapped value buried in complex data."
    buttonText = "Get Started"
    downloadText = "VIEW ON GITHUB"
    githubLink = "https://github.com/vesoft-inc/nebula"
    class = "download"
    link = "https://docs.nebula-graph.io/manual-EN/1.overview/2.quick-start/1.get-started"

  # Footer section
  [params.footer]
    name = "contact_us"
    [params.footer.social]
      title = "Follow us on"
      [[params.footer.social.links]]
          title = "Twitter"
          class = "icon fa fa-twitter"
          pic = "twitter.png"
          link = "https://twitter.com/NebulaGraph"
          target = "_blank"
      [[params.footer.social.links]]
          title = "LinkedIn"
          class = "icon fa fa-linkedin"
          pic = "linkedin.png"
          link = "https://www.linkedin.com/company/vesoft-nebula-graph/"
          target = "_blank"
      [[params.footer.social.links]]
          title = "YouTube"
          class = "icon fa fa-youtube"
          pic = "youtube.png"
          link = "https://www.youtube.com/channel/UC73V8q795eSEMxDX4Pvdwmw"
          target = "_blank"
      [[params.footer.social.links]]
          title = "FaceBook"
          class = "icon fa fa-facebook"
          pic = "facebook.png"
          link = "https://www.facebook.com/NebulaGraph/"
          target = "_blank"
      [[params.footer.social.links]]
          title = "WeiBo"
          class = "icon fa fa-weibo"
          pic = "weibo.png"
          link = "https://weibo.com/nebulagraph"
          target = "_blank"
      [[params.footer.social.links]]
          title = "Official Accounts"
          class = "icon fa fa-wechat"
          pic = "gongzhonghao.png"
          id = "#myGongzhonghaoModal"
          target = "_blank"
  
    [[params.footer.community]]
      title = "Community"
      [[params.footer.community.links]]
          title = "GitHub"
          pic = "github.png"
          link = "https://github.com/vesoft-inc/nebula"
          target = "_blank"
      [[params.footer.community.links]]
          title = "Forum"
          pic = "forum.png"
          link = "https://discuss.nebula-graph.io/"
          target = "_blank"
      [[params.footer.community.links]]
          title = "Slack"
          pic = "slack.png"
          link = "https://join.slack.com/t/nebulagraph/shared_invite/enQtNjIzMjQ5MzE2OTQ2LTM0MjY0MWFlODg3ZTNjMjg3YWU5ZGY2NDM5MDhmOGU2OWI5ZWZjZDUwNTExMGIxZTk2ZmQxY2Q2MzM1OWJhMmY#"
          target = "_blank"
    [[params.footer.contactus]]
      title = "Contact Us"
      [[params.footer.contactus.links]]
          title = "(+86) 0571-28120658"
          link = ""
          pic = "iphone.png"
          target = "_blank"
      [[params.footer.contactus.links]]
          title = "info@vesoft.com"
          link = "mailto:info@vesoft.com"
          pic = "email.png"
          target = "_blank"
      [[params.footer.contactus.links]]
          title = "WeChat"
          link = ""
          id = "#myModal"
          pic = "weixin.png"
          target = "_blank"
    

  # [params.advantage]
  #   headline    = "Why Nebula"
  #   description = "blablablabla..."
  #   buttonText  = "Get started!"


  # Service section
  [params.features]
    headline = "Nebula Graph Features"

      [[params.features.list]]
        pic = "feature1.png"
        title = "Open Source"
        link = "https://discuss.nebula-graph.io/"
        description1 = "We are continuing to"
        description2 = "collaborate with the community"
        description3 = "to prepare, popularize and promote the graph database."

      [[params.features.list]]
        pic = "feature4.png"
        title = "Secure"
        link = "https://nebula-graph.io/posts/access-control-design-code-nebula-graph/"
        description1 = "Nebula Graph only allows authenticated access via "
        description2 = "role-based access control"
        description3 = "."

      [[params.features.list]]
        pic = "feature6.png"
        title = "Extensible"
        link = "https://nebula-graph.io/en/posts/nebula-graph-storage-engine-overview/"
        description1 = "Nebula Graph supports multiple  "
        description2 = "storage engine"
        description3 = " types and the query language can be extended to support new algorithms."

      [[params.features.list]]
        pic = "feature2.png"
        title = "Performant"
        link = "https://discuss.nebula-graph.io/t/nebula-graph-1-0-benchmark-report/581"
        description1 = "Nebula Graph provides "
        description2 = "low latency read and write"
        description3 = ", while still maintaining high throughput to simplify the most complex data sets."

      
      [[params.features.list]]
        pic = "feature5.png"
        title = "Scalable"
        link = "https://nebula-graph.io/en/posts/nebula-graph-architecture-overview/"
        description1 = "With a shared-nothing "
        description2 = "distributed architecture"
        description3 = ", Nebula Graph offers linear scalability."

      [[params.features.list]]
        pic = "feature3.png"
        title = "SQL-like"
        link = "https://docs.nebula-graph.io/manual-EN/1.overview/1.concepts/2.nGQL-overview/"
        description1 = "Nebula Graph's SQL-like "
        description2 = "query language"
        description3 = "is easy to understand and powerful enough to meet complex business needs."

      [[params.features.list]]
        pic = "feature8.png"
        title = "Highly Available"
        description = "Nebula Graph guarantees high availability even in case of failures."
        link = "https://nebula-graph.io/en/posts/nebula-graph-snapshot-introduction/"
        description1 = "With horizontal scalability and a "
        description2 = "snapshot"
        description3 = "feature, Nebula Graph guarantees high availability even in case of failures."

      [[params.features.list]]
        pic = "feature7.png"
        title = "Production Ready"
        link = "https://discuss.nebula-graph.io/t/what-customers-say-about-nebula-graph/580"
        description1 = "Large Internet companies like JD, Meituan, and Xiaohongshu have deployed Nebula Graph in production environments."
        description2 = " They chose Nebula Graph for some common reasons"
        description3 = "."

  # [params.portfolio.modal]
  #       client = "Client"
  #       date = "Date"
  #       category = "Category"
  #       buttonText = "Close"

  # Contact section
  [params.contact]
    headline = "Let's Get In Touch!"
    description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
    phone = "123-456-6789"
    email = "feedback@startbootstrap.com"
  # blog section
  [params.blog]
    title = "Contents"
  # Tags
  [params.tags]
    title = "Tags"
    all = "all"
    pic = "LabelTagIcon.png"
  [[params.links]]
    text = "Star us"
    link = "https://github.com/vesoft-inc/nebula"
    image = "/images/good.png"
    onclick = "gtag('event', 'Link Click', { event_category: 'Engagement', event_label: 'Star via sidebar'})"
  [[params.links]]
    text = "Subscribe RSS"
    link = "https://nebula-graph.io/posts/index.xml"
    image = "/images/rss1.png"
    onclick = "gtag('event', 'Link Click', { event_category: 'Engagement', event_label: 'RSS on sidebar'})"
  [params.share]
    title = "Share"
    star = "Like what we do? Star us on GitHub.  https://github.com/vesoft-inc/nebula"
  [params.rss]
    link = "https://nebula-graph.io/posts/index.xml"


  
