contentDir = "content/en"
[params]
  # Releases section
  [params.releases]
      pic = "download.png"
      downloadLink = "/file/NebulaGraphMediaKit.zip"
      title="Press Releases"
      readMore = "Read More >>"
      link = "/news"
      releaseTitle="Nebula Graph Media Coverage | Press Releases"
      description="Press releases on the Nebula Graph database, mainly about product releases and feature updates."
      [[params.releases.list]]
        pic = "feature4.png"
        title = "Nebula Graph™ Database Raises $8 Million in Series Pre-A Funding"
        date = "June 15, 2020"
        readMore = "Read More >>"
        link = "https://nebula-graph.io/posts/nebula-graph-raises-8-million-dollars-in-series-pre-a-funding/"
        Description = "VEsoft Inc., the developer of the Nebula Graph™ database, today announced it raised $8M in a series pre-A funding round. The lead investor is Redpoint China Ventures. Matrix Partners China, who previously contributed as an angel investor, also contributed to this series pre-A round.a "

      [[params.releases.list]]
        pic = "feature4.png"
        title = "The World’s Most Capable Graph Database, Nebula Graph™, Debuts for Unmatched Big Data Analytics Discovery"
        date = "June 29, 2020"
        readMore = "Read More >>"
        link = "https://nebula-graph.io/posts/nebula-graph-1.0-release/"
        Description = "Nebula Graph™ is now commercially available as the only database that can store and process billions of data points with trillions of relational connections in a shared-nothing distributed architecture for the industry’s best business continuity."  

      [[params.releases.list]]
        pic = "feature4.png"
        title = "The World’s Most Capable Graph Database, Nebula Graph™, Debuts for Unmatched Big Data Analytics Discovery"
        date = "June 29, 2020"
        readMore = "Read More >>"
        link = "https://nebula-graph.io/posts/nebula-graph-1.0-release/"
        Description = "Nebula Graph™ is now commercially available as the only database that can store and process billions of data points with trillions of relational connections in a shared-nothing distributed architecture for the industry’s best business continuity."  